#!/bin/bash
BASE="http://localhost:8082/api"

echo "=== KULLANICILAR KAYDEDILIYOR ==="
U2=$(curl -s -X POST $BASE/users/register -H "Content-Type: application/json" -d '{"email":"ayse@campus.com","password":"password123","studentNumber":"2021002","firstName":"Ayse","lastName":"Yilmaz"}' | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
U3=$(curl -s -X POST $BASE/users/register -H "Content-Type: application/json" -d '{"email":"mehmet@campus.com","password":"password123","studentNumber":"2021003","firstName":"Mehmet","lastName":"Kaya"}' | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
U4=$(curl -s -X POST $BASE/users/register -H "Content-Type: application/json" -d '{"email":"zeynep@campus.com","password":"password123","studentNumber":"2021004","firstName":"Zeynep","lastName":"Celik"}' | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
U5=$(curl -s -X POST $BASE/users/register -H "Content-Type: application/json" -d '{"email":"emre@campus.com","password":"password123","studentNumber":"2021005","firstName":"Emre","lastName":"Demir"}' | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
U6=$(curl -s -X POST $BASE/users/register -H "Content-Type: application/json" -d '{"email":"fatma@campus.com","password":"password123","studentNumber":"2021006","firstName":"Fatma","lastName":"Sahin"}' | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
U7=$(curl -s -X POST $BASE/users/register -H "Content-Type: application/json" -d '{"email":"baris@campus.com","password":"password123","studentNumber":"2021007","firstName":"Baris","lastName":"Arslan"}' | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
U8=$(curl -s -X POST $BASE/users/register -H "Content-Type: application/json" -d '{"email":"selin@campus.com","password":"password123","studentNumber":"2021008","firstName":"Selin","lastName":"Ozturk"}' | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
U9=$(curl -s -X POST $BASE/users/register -H "Content-Type: application/json" -d '{"email":"can@campus.com","password":"password123","studentNumber":"2021009","firstName":"Can","lastName":"Yildiz"}' | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
U10=$(curl -s -X POST $BASE/users/register -H "Content-Type: application/json" -d '{"email":"merve@campus.com","password":"password123","studentNumber":"2021010","firstName":"Merve","lastName":"Koc"}' | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
U1=10003
echo "Kullanicilar: U1=$U1 U2=$U2 U3=$U3 U4=$U4 U5=$U5 U6=$U6 U7=$U7 U8=$U8 U9=$U9 U10=$U10"

echo "=== TOKENLAR ALINIYOR ==="
T1=$(curl -s -X POST $BASE/users/login -H "Content-Type: application/json" -d '{"email":"ali@campus.com","password":"password123"}' | python3 -c "import sys,json; print(json.load(sys.stdin)['token'])")
T2=$(curl -s -X POST $BASE/users/login -H "Content-Type: application/json" -d '{"email":"ayse@campus.com","password":"password123"}' | python3 -c "import sys,json; print(json.load(sys.stdin)['token'])")
T3=$(curl -s -X POST $BASE/users/login -H "Content-Type: application/json" -d '{"email":"mehmet@campus.com","password":"password123"}' | python3 -c "import sys,json; print(json.load(sys.stdin)['token'])")
T4=$(curl -s -X POST $BASE/users/login -H "Content-Type: application/json" -d '{"email":"zeynep@campus.com","password":"password123"}' | python3 -c "import sys,json; print(json.load(sys.stdin)['token'])")
T5=$(curl -s -X POST $BASE/users/login -H "Content-Type: application/json" -d '{"email":"emre@campus.com","password":"password123"}' | python3 -c "import sys,json; print(json.load(sys.stdin)['token'])")
echo "Tokenlar alindi."

echo "=== ILANLAR EKLENIYOR ==="
I1=$(curl -s -X POST $BASE/catalog/items -H "Content-Type: application/json" -H "Authorization: Bearer $T1" -d "{\"title\":\"Canon EOS 90D DSLR\",\"description\":\"Sadece 3 kere kullanildi, hafiza karti dahil.\",\"category\":\"Kamera\",\"dailyPrice\":200.0,\"condition\":\"NEW\",\"ownerUserId\":$U1}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
I2=$(curl -s -X POST $BASE/catalog/items -H "Content-Type: application/json" -H "Authorization: Bearer $T1" -d "{\"title\":\"Yazilim Muhendisligi - Sommerville\",\"description\":\"10. baski, temiz, alti cizili sayfa yok.\",\"category\":\"Kitap\",\"dailyPrice\":35.0,\"condition\":\"GOOD\",\"ownerUserId\":$U1}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
I3=$(curl -s -X POST $BASE/catalog/items -H "Content-Type: application/json" -H "Authorization: Bearer $T1" -d "{\"title\":\"Profesyonel Tripod\",\"description\":\"Aluminyum govde, her kamera ile uyumlu.\",\"category\":\"Kamera\",\"dailyPrice\":50.0,\"condition\":\"GOOD\",\"ownerUserId\":$U1}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
I4=$(curl -s -X POST $BASE/catalog/items -H "Content-Type: application/json" -H "Authorization: Bearer $T2" -d "{\"title\":\"Kamp Cadiri 3 Kisilik\",\"description\":\"Su gecirmez, fermuarlari saglam.\",\"category\":\"Kamp\",\"dailyPrice\":150.0,\"condition\":\"GOOD\",\"ownerUserId\":$U2}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
I5=$(curl -s -X POST $BASE/catalog/items -H "Content-Type: application/json" -H "Authorization: Bearer $T2" -d "{\"title\":\"Uyku Tulumu -5 Derece\",\"description\":\"Kaz tuyu dolgulu, temizlenip teslim edilecek.\",\"category\":\"Kamp\",\"dailyPrice\":80.0,\"condition\":\"GOOD\",\"ownerUserId\":$U2}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
I6=$(curl -s -X POST $BASE/catalog/items -H "Content-Type: application/json" -H "Authorization: Bearer $T2" -d "{\"title\":\"Elektrikli Gitar + Amfi\",\"description\":\"Amfi dahil, baslangic seviyesi icin uygun.\",\"category\":\"Muzik\",\"dailyPrice\":120.0,\"condition\":\"FAIR\",\"ownerUserId\":$U2}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
I7=$(curl -s -X POST $BASE/catalog/items -H "Content-Type: application/json" -H "Authorization: Bearer $T3" -d "{\"title\":\"Sony PlayStation 5 + 2 Kol\",\"description\":\"FIFA ve GTA dahil, kutusunda.\",\"category\":\"Elektronik\",\"dailyPrice\":250.0,\"condition\":\"GOOD\",\"ownerUserId\":$U3}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
I8=$(curl -s -X POST $BASE/catalog/items -H "Content-Type: application/json" -H "Authorization: Bearer $T3" -d "{\"title\":\"Nintendo Switch OLED\",\"description\":\"Kablo ve dok dahil, ekranda cizik yok.\",\"category\":\"Elektronik\",\"dailyPrice\":200.0,\"condition\":\"GOOD\",\"ownerUserId\":$U3}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
I9=$(curl -s -X POST $BASE/catalog/items -H "Content-Type: application/json" -H "Authorization: Bearer $T3" -d "{\"title\":\"Bilgisayar Aglari - Kurose Ross\",\"description\":\"8. baski, Turkce notlar var.\",\"category\":\"Kitap\",\"dailyPrice\":30.0,\"condition\":\"FAIR\",\"ownerUserId\":$U3}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
I10=$(curl -s -X POST $BASE/catalog/items -H "Content-Type: application/json" -H "Authorization: Bearer $T4" -d "{\"title\":\"Elektrikli Scooter\",\"description\":\"Kampus ici ulasim icin birebir. 40km menzil.\",\"category\":\"Ulasim\",\"dailyPrice\":300.0,\"condition\":\"GOOD\",\"ownerUserId\":$U4}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
I11=$(curl -s -X POST $BASE/catalog/items -H "Content-Type: application/json" -H "Authorization: Bearer $T4" -d "{\"title\":\"Yoga Mati + Pilates Seti\",\"description\":\"Kaymaz, 6mm kalinlik, top dahil.\",\"category\":\"Spor\",\"dailyPrice\":40.0,\"condition\":\"NEW\",\"ownerUserId\":$U4}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
I12=$(curl -s -X POST $BASE/catalog/items -H "Content-Type: application/json" -H "Authorization: Bearer $T4" -d "{\"title\":\"Drone DJI Mini 2\",\"description\":\"Uzaktan kumanda ve yedek pil dahil, 4K.\",\"category\":\"Elektronik\",\"dailyPrice\":400.0,\"condition\":\"GOOD\",\"ownerUserId\":$U4}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
I13=$(curl -s -X POST $BASE/catalog/items -H "Content-Type: application/json" -H "Authorization: Bearer $T5" -d "{\"title\":\"Bisiklet - 27.5 Jant Mountain Bike\",\"description\":\"Vites sistemi sorunsuz, kilit ve kask dahil.\",\"category\":\"Ulasim\",\"dailyPrice\":180.0,\"condition\":\"GOOD\",\"ownerUserId\":$U5}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
I14=$(curl -s -X POST $BASE/catalog/items -H "Content-Type: application/json" -H "Authorization: Bearer $T5" -d "{\"title\":\"Gitar Akustik Yamaha\",\"description\":\"Baslangic icin ideal, teller yeni takildi.\",\"category\":\"Muzik\",\"dailyPrice\":60.0,\"condition\":\"GOOD\",\"ownerUserId\":$U5}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
echo "Ilanlar: I1=$I1 I2=$I2 I3=$I3 I4=$I4 I5=$I5 I6=$I6 I7=$I7 I8=$I8 I9=$I9 I10=$I10 I11=$I11 I12=$I12 I13=$I13 I14=$I14"

echo "=== KIRALAMALAR OLUSTURULUYOR ==="
R1=$(curl -s -X POST $BASE/rentals -H "Content-Type: application/json" -H "Authorization: Bearer $T1" -d "{\"itemId\":$I7,\"renterUserId\":$U1,\"ownerUserId\":$U3,\"startDate\":\"2026-05-19\",\"endDate\":\"2026-05-23\",\"totalPrice\":1000.0,\"status\":\"COMPLETED\"}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
R2=$(curl -s -X POST $BASE/rentals -H "Content-Type: application/json" -H "Authorization: Bearer $T3" -d "{\"itemId\":$I4,\"renterUserId\":$U3,\"ownerUserId\":$U2,\"startDate\":\"2026-05-19\",\"endDate\":\"2026-05-22\",\"totalPrice\":450.0,\"status\":\"COMPLETED\"}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
R3=$(curl -s -X POST $BASE/rentals -H "Content-Type: application/json" -H "Authorization: Bearer $T2" -d "{\"itemId\":$I13,\"renterUserId\":$U2,\"ownerUserId\":$U5,\"startDate\":\"2026-05-19\",\"endDate\":\"2026-05-22\",\"totalPrice\":540.0,\"status\":\"COMPLETED\"}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
R4=$(curl -s -X POST $BASE/rentals -H "Content-Type: application/json" -H "Authorization: Bearer $T5" -d "{\"itemId\":$I1,\"renterUserId\":$U5,\"ownerUserId\":$U1,\"startDate\":\"2026-05-19\",\"endDate\":\"2026-05-21\",\"totalPrice\":400.0,\"status\":\"COMPLETED\"}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
R5=$(curl -s -X POST $BASE/rentals -H "Content-Type: application/json" -H "Authorization: Bearer $T4" -d "{\"itemId\":$I12,\"renterUserId\":$U4,\"ownerUserId\":$U4,\"startDate\":\"2026-05-20\",\"endDate\":\"2026-05-22\",\"totalPrice\":800.0,\"status\":\"ACTIVE\"}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
R6=$(curl -s -X POST $BASE/rentals -H "Content-Type: application/json" -H "Authorization: Bearer $T3" -d "{\"itemId\":$I8,\"renterUserId\":$U3,\"ownerUserId\":$U3,\"startDate\":\"2026-05-20\",\"endDate\":\"2026-05-24\",\"totalPrice\":800.0,\"status\":\"ACTIVE\"}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
R7=$(curl -s -X POST $BASE/rentals -H "Content-Type: application/json" -H "Authorization: Bearer $T1" -d "{\"itemId\":$I10,\"renterUserId\":$U1,\"ownerUserId\":$U4,\"startDate\":\"2026-05-25\",\"endDate\":\"2026-05-28\",\"totalPrice\":900.0,\"status\":\"APPROVED\"}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
R8=$(curl -s -X POST $BASE/rentals -H "Content-Type: application/json" -H "Authorization: Bearer $T2" -d "{\"itemId\":$I6,\"renterUserId\":$U2,\"ownerUserId\":$U2,\"startDate\":\"2026-05-26\",\"endDate\":\"2026-05-29\",\"totalPrice\":360.0,\"status\":\"PENDING\"}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
R9=$(curl -s -X POST $BASE/rentals -H "Content-Type: application/json" -H "Authorization: Bearer $T5" -d "{\"itemId\":$I11,\"renterUserId\":$U5,\"ownerUserId\":$U4,\"startDate\":\"2026-05-27\",\"endDate\":\"2026-05-30\",\"totalPrice\":120.0,\"status\":\"PENDING\"}" | python3 -c "import sys,json; print(json.load(sys.stdin)['id'])")
echo "Kiralamalar: R1=$R1 R2=$R2 R3=$R3 R4=$R4 R5=$R5 R6=$R6 R7=$R7 R8=$R8 R9=$R9"

echo "=== YORUMLAR EKLENIYOR ==="
curl -s -X POST $BASE/reviews -H "Content-Type: application/json" -H "Authorization: Bearer $T1" -d "{\"rentalId\":$R1,\"reviewerUserId\":$U1,\"targetUserId\":$U3,\"itemId\":$I7,\"rating\":5,\"comment\":\"PS5 tertemizdi, Mehmet cok guvenilir. Kesinlikle tavsiye ederim!\"}" > /dev/null
curl -s -X POST $BASE/reviews -H "Content-Type: application/json" -H "Authorization: Bearer $T3" -d "{\"rentalId\":$R1,\"reviewerUserId\":$U3,\"targetUserId\":$U1,\"itemId\":$I7,\"rating\":4,\"comment\":\"Ali zamaninda teslim etti, iletisim cok iyiydi.\"}" > /dev/null
curl -s -X POST $BASE/reviews -H "Content-Type: application/json" -H "Authorization: Bearer $T3" -d "{\"rentalId\":$R2,\"reviewerUserId\":$U3,\"targetUserId\":$U2,\"itemId\":$I4,\"rating\":5,\"comment\":\"Cador mukemmel durumda, Ayse harika bir deneyim sundu!\"}" > /dev/null
curl -s -X POST $BASE/reviews -H "Content-Type: application/json" -H "Authorization: Bearer $T2" -d "{\"rentalId\":$R3,\"reviewerUserId\":$U2,\"targetUserId\":$U5,\"itemId\":$I13,\"rating\":4,\"comment\":\"Bisiklet iyi durumda, Emre yardimci oldu.\"}" > /dev/null
curl -s -X POST $BASE/reviews -H "Content-Type: application/json" -H "Authorization: Bearer $T5" -d "{\"rentalId\":$R4,\"reviewerUserId\":$U5,\"targetUserId\":$U1,\"itemId\":$I1,\"rating\":5,\"comment\":\"Canon kamera kusursuzdu, Ali profesyonel biriydi.\"}" > /dev/null
echo "Yorumlar eklendi."

echo ""
echo "========================================="
echo " TUM VERILER BASARIYLA YUKLENDI!"
echo " Giris: ali@campus.com / password123"
echo "========================================="
