spring.application.name=rental-service
server.port=8084

# SQL Server
spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=CampusShare_RentalDB;encrypt=false;trustServerCertificate=true}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:mahir0506093Aa}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka Client
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8061/eureka

eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name} - ${server.port}
eureka.instance.prefer-ip-address=true 
# hostname yerine ip adresiyle kaydet eurekaya her yerde calısır !