spring.application.name=app
spring.datasource.username=sa
spring.datasource.password=mahir0506093Aa

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CampusShare_UserDB;encrypt=false;trustServerCertificate=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.default_schema=dbo
spring.jpa.hibernate.ddl-auto=create

jwt.secret=dGhpc0lzQVNlY3VyZUtleUZvckp3dDEyMzQ1Njc4OTA=

jwt.expire=86400000
